#!/bin/sh

# Download the list of words.
curl -o /tmp/words.txt \
     https://raw.githubusercontent.com/dwyl/english-words/master/words.txt

# Make the script executable.
chmod +x grus-add

# Add those words to the database.
./grus-add \
    -d $HOME/.local/share/grus/grus.db \
    -f /tmp/words.txt
